"use strict";
const API_BASE=window.HINTAI_API_URL||"/api";
const state={credits:20,streak:0,xp:0,level:1,solved:0,currentResponseId:null,currentPage:"home",history:[]};
const $=id=>document.getElementById(id);
const save=()=>{try{localStorage.setItem("hintai_state",JSON.stringify(state))}catch(e){}};
function load(){try{const x=JSON.parse(localStorage.getItem("hintai_state")||"null");if(x)Object.assign(state,x)}catch(e){}}
function uid(){let x=localStorage.getItem("hintai_user_id");if(!x){x=`anon_${Date.now()}_${Math.random().toString(36).slice(2)}`;localStorage.setItem("hintai_user_id",x)}return x}
function headers(json=false){const h={"X-User-ID":uid()};const t=localStorage.getItem("hintai_token");if(t)h.Authorization=`Bearer ${t}`;if(json)h["Content-Type"]="application/json";return h}
function showScreen(name){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===`screen-${name}`));document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===name));state.currentPage=name;save()}
function toast(message,type="info"){let c=$("toastContainer");if(!c){c=document.createElement("div");c.id="toastContainer";c.className="toast-container";document.body.appendChild(c)}const t=document.createElement("div");t.className=`toast toast-${type}`;t.textContent=message;c.appendChild(t);requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>t.remove(),3500)}
function ui(){["credits","homeCredits","profileCredits"].forEach(id=>{if($(id))$(id).textContent=Math.max(0,state.credits)});if($("homeXp"))$("homeXp").textContent=state.xp;if($("profileXp"))$("profileXp").textContent=state.xp;if($("homeLevel"))$("homeLevel").textContent=state.level;if($("profileLevel"))$("profileLevel").textContent=state.level;if($("homeSolved"))$("homeSolved").textContent=state.solved;if($("profileSolved2"))$("profileSolved2").textContent=state.solved;if($("profileStreak"))$("profileStreak").textContent=`${state.streak} j`;if($("profileStreak2"))$("profileStreak2").textContent=state.streak;if($("xpProgress"))$("xpProgress").style.width=`${state.xp%100}%`}
function spend(n){if(state.credits<n){toast("Crédits insuffisants.","warning");return false}state.credits-=n;ui();save();return true}
function progress(n=10){state.xp+=n;state.level=Math.floor(state.xp/100)+1;state.solved++;state.streak=Math.max(1,state.streak);ui();save()}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function addHistory(label){state.history.unshift({label,at:new Date().toLocaleString("fr-FR")});state.history=state.history.slice(0,20);const b=$("history");if(b)b.innerHTML=state.history.map(x=>`<div class="history-item"><span>✓</span><div><strong>${esc(x.label)}</strong><small>${esc(x.at)}</small></div></div>`).join("");save()}
async function api(path,options={}){const r=await fetch(`${API_BASE}${path}`,options);let d=null;try{d=await r.json()}catch(e){}if(!r.ok)throw Object.assign(new Error(d?.detail||d?.error?.message||`Erreur ${r.status}`),{status:r.status});return d}
function display(text){const b=$("response");if(b){b.textContent=text||"Aucune réponse.";b.classList.remove("ai-response");void b.offsetWidth;b.classList.add("ai-response")}}
async function analyse(){const text=$("exerciseInput")?.value.trim();const file=$("fileInput")?.files?.[0];if(!text&&!file)return toast("Ajoute un exercice ou un fichier.","warning");if(!spend(2))return;display("Analyse en cours…");try{let fileId=null;if(file){const f=new FormData();f.append("file",file);const u=await api("/api/upload",{method:"POST",headers:headers(),body:f});fileId=u.fileId||u.file_id}const d=await api("/api/help-me/start",{method:"POST",headers:headers(true),body:JSON.stringify({inputType:file?.type||"text",text:text||"",fileId})});state.currentResponseId=d.responseId||d.response_id;display(d.text||d.answer);progress(10);addHistory("Analyse d’un exercice")}catch(e){display(e.message);toast(e.message,"error")}}
async function hint(){if(!state.currentResponseId)return toast("Analyse d'abord un exercice.","warning");if(!spend(1))return;try{const d=await api("/api/help-me/hint/1",{method:"POST",headers:headers(true),body:JSON.stringify({responseId:state.currentResponseId})});display(d.text||d.answer);addHistory("Indice demandé")}catch(e){toast(e.message,"error")}}
async function solution(){if(!state.currentResponseId)return toast("Analyse d'abord un exercice.","warning");if(!spend(2))return;try{const d=await api("/api/help-me/solution",{method:"POST",headers:headers(true),body:JSON.stringify({responseId:state.currentResponseId})});display(d.text||d.answer);progress(15);addHistory("Solution complète")}catch(e){toast(e.message,"error")}}
async function learn(){const concept=$("conceptInput")?.value.trim();if(!concept)return toast("Indique un concept.","warning");if(!spend(2))return;display("Préparation de l'explication…");try{const d=await api("/api/learn-concept/start",{method:"POST",headers:headers(true),body:JSON.stringify({concept})});display(d.text||d.answer);progress(10);addHistory(`Apprentissage : ${concept}`)}catch(e){toast(e.message,"error")}}
function upload(){const i=$("fileInput");if(!i)return;$("cameraBtn")?.addEventListener("click",()=>{i.accept="image/*";i.setAttribute("capture","environment");i.click()});$("pdfBtn")?.addEventListener("click",()=>{i.accept="application/pdf,.pdf";i.removeAttribute("capture");i.click()});i.addEventListener("change",()=>{const f=i.files?.[0];if($("fileStatus"))$("fileStatus").textContent=f?`${f.name} · ${(f.size/1048576).toFixed(1)} Mo`:"Aucun fichier sélectionné."})}
function init(){load();ui();document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.page)));document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.go)));$("analyseBtn")?.addEventListener("click",analyse);$("hintBtn")?.addEventListener("click",hint);$("solutionBtn")?.addEventListener("click",solution);$("learnStartBtn")?.addEventListener("click",learn);upload();showScreen(state.currentPage||"home")}
document.addEventListener("DOMContentLoaded",init);