const API_BASE=window.HINTAI_API_URL||"https://hintai-ai-v2.onrender.com";
const STORAGE_KEY="hintai_state";
const state={credits:20,streak:0,xp:0,level:1,solved:0,currentResponseId:null,currentPage:"home",history:[]};
const $=id=>document.getElementById(id);
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch(e){}}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY)||"null");if(x)Object.assign(state,x)}catch(e){}}
function userId(){let id=localStorage.getItem("hintai_user_id");if(!id){id=`anon_${crypto.randomUUID?crypto.randomUUID():Date.now()}`;localStorage.setItem("hintai_user_id",id)}return id}
function headers(json=false){const h={"X-User-ID":userId()};const token=localStorage.getItem("hintai_token");if(token)h.Authorization=`Bearer ${token}`;if(json)h["Content-Type"]="application/json";return h}
function showScreen(name){document.querySelectorAll(".screen").forEach(s=>s.classList.toggle("active",s.id===`screen-${name}`));document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.page===name));state.currentPage=name;save();window.scrollTo({top:0,behavior:"smooth"})}
function ui(){["credits","homeCredits","profileCredits"].forEach(id=>{if($(id))$(id).textContent=Math.max(0,state.credits)});if($("profileStreak"))$("profileStreak").textContent=state.streak+" j";if($("profileStreak2"))$("profileStreak2").textContent=state.streak;if($("homeXp"))$("homeXp").textContent=state.xp;if($("profileXp"))$("profileXp").textContent=state.xp;if($("homeLevel"))$("homeLevel").textContent=state.level;if($("profileLevel"))$("profileLevel").textContent=state.level;if($("homeSolved"))$("homeSolved").textContent=state.solved;if($("profileSolved2"))$("profileSolved2").textContent=state.solved;if($("xpProgress"))$("xpProgress").style.width=`${state.xp%100}%`}
function toast(msg,type="info"){let c=$("toastContainer");if(!c){c=document.createElement("div");c.id="toastContainer";c.className="toast-container";document.body.appendChild(c)}const t=document.createElement("div");t.className=`toast toast-${type}`;t.textContent=msg;c.appendChild(t);requestAnimationFrame(()=>t.classList.add("show"));setTimeout(()=>{t.classList.remove("show");setTimeout(()=>t.remove(),250)},3500)}
function spend(n){if(state.credits<n){toast("Crédits insuffisants.","warning");return false}state.credits-=n;ui();save();return true}
function progress(x=10){state.xp+=x;state.level=Math.floor(state.xp/100)+1;state.solved++;state.streak=Math.max(1,state.streak);ui();save()}
function escape(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]))}
function history(label){state.history.unshift({label,at:new Date().toLocaleString("fr-FR")});state.history=state.history.slice(0,20);const b=$("history");if(b)b.innerHTML=state.history.map(x=>`<div class="history-item"><span>✓</span><div><strong>${escape(x.label)}</strong><small>${escape(x.at)}</small></div></div>`).join("");save()}
async function request(path,opts={}){const r=await fetch(`${API_BASE}${path}`,opts);let d=null;try{d=await r.json()}catch(e){}if(!r.ok){const e=new Error(d?.detail||"Erreur serveur");e.status=r.status;throw e}return d}
function display(d){const b=$("response");if(!b)return;b.textContent=d?.text||d?.answer||"Aucune réponse.";b.classList.remove("ai-response");void b.offsetWidth;b.classList.add("ai-response")}
async function analyse(){const text=$("exerciseInput")?.value.trim(),file=$("fileInput")?.files?.[0];if(!text&&!file)return toast("Ajoute un exercice ou un fichier.","warning");if(!spend(2))return;display({text:"Analyse en cours…"});try{let fileId=null;if(file){const f=new FormData();f.append("file",file);const u=await request("/api/upload",{method:"POST",headers:headers(),body:f});fileId=u.fileId||u.file_id}const d=await request("/api/help-me/start",{method:"POST",headers:headers(true),body:JSON.stringify({inputType:file?.type||"text",text:text||"",fileId})});state.currentResponseId=d.responseId||d.response_id;display(d);progress(10);history("Analyse d’un exercice")}catch(e){display({text:e.message});toast(e.message,"error")}}
async function hint(){if(!state.currentResponseId)return toast("Analyse d'abord un exercice.","warning");if(!spend(1))return;try{display(await request("/api/help-me/hint/1",{method:"POST",headers:headers(true),body:JSON.stringify({responseId:state.currentResponseId})}));history("Indice demandé")}catch(e){toast(e.message,"error")}}
async function solution(){if(!state.currentResponseId)return toast("Analyse d'abord un exercice.","warning");if(!spend(2))return;try{display(await request("/api/help-me/solution",{method:"POST",headers:headers(true),body:JSON.stringify({responseId:state.currentResponseId})}));progress(15);history("Solution complète")}catch(e){toast(e.message,"error")}}
async function learn(){const concept=$("conceptInput")?.value.trim();if(!concept)return toast("Indique un concept.","warning");if(!spend(2))return;display({text:"Préparation de l'explication…"});try{display(await request("/api/learn-concept/start",{method:"POST",headers:headers(true),body:JSON.stringify({concept})}));progress(10);history(`Apprentissage : ${concept}`)}catch(e){toast(e.message,"error")}}
function upload(){const i=$("fileInput");if(!i)return;$("cameraBtn")?.addEventListener("click",()=>{i.accept="image/*";i.setAttribute("capture","environment");i.click()});$("pdfBtn")?.addEventListener("click",()=>{i.accept="application/pdf,.pdf";i.removeAttribute("capture");i.click()});i.addEventListener("change",()=>{const f=i.files?.[0];if($("fileStatus"))$("fileStatus").textContent=f?`${f.name} · ${(f.size/1048576).toFixed(1)} Mo`:"Aucun fichier sélectionné."})}
function init(){load();ui();document.querySelectorAll("[data-page]").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.page)));document.querySelectorAll("[data-go]").forEach(b=>b.addEventListener("click",()=>showScreen(b.dataset.go)));$("analyseBtn")?.addEventListener("click",analyse);$("hintBtn")?.addEventListener("click",hint);$("solutionBtn")?.addEventListener("click",solution);$("learnStartBtn")?.addEventListener("click",learn);upload();showScreen(state.currentPage||"home")}
document.addEventListener("DOMContentLoaded",init);